### ISSUE TITLE
Refresh Header Text Bugging Routes

### ISSUE THREAD

**Issue by riley-thomps** [Gopher-X-Metro/Gopher-X-Metro#88]
Clicking our _Gopher X Metro_ header text reloads the page as expected. However, if you have routes selected when you click the header, after the refresh those routes stay bugged in. Even though the url has updated by removing them from the query parameters, those buses and routes still appear on the map and _seem_ selected in the navbar even though it _technically_ is not. You also **cannot** reactive this _bugged_ route in the navbar by reclicking it, it stays locked in. If you then go and try to select a **different** route, it then inactivates those _bugged_ routes, and the url and navbar seem to be sync again. 

This is an important bug to fix since its our main refresh mechanism outside of refreshing the entire webpage in the browser.

**Comment by KennedyJohnson** [comment]
made some progress on this issue, still working through some bugs

**Comment by KennedyJohnson** [comment]
fixed in sidebar-favorites
